ID	ALIGNMENT	COGID	TOKENS	SUBGROUP	CONCEPT	PROTO_FORM	DOCULECT	FORM	NOTE
<!--: spam
Content-Type: text/html

<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> -->
<body bgcolor="#f0f0f8"><font color="#f0f0f8" size="-5"> --> -->
</font> </font> </font> </script> </object> </blockquote> </pre>
</table> </table> </table> </table> </table> </font> </font> </font><body bgcolor="#f0f0f8">
<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">
<tr bgcolor="#6622aa">
<td valign=bottom>&nbsp;<br>
<font color="#ffffff" face="helvetica, arial">&nbsp;<br><big><big><strong>&lt;class 'sqlite3.OperationalError'&gt;</strong></big></big></font></td
><td align=right valign=bottom
><font color="#ffffff" face="helvetica, arial">Python 2.7.12: /usr/bin/python2.7<br>Mon Jul 17 15:01:51 2023</font></td></tr></table>
    
<p>A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.</p>
<table width="100%" cellspacing=0 cellpadding=0 border=0>
<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file:///home/m2121/Sites/lingulist.de/edictor/triples/get_data.py">/home/m2121/Sites/lingulist.de/edictor/triples/get_data.py</a> in <strong><module></strong>()</td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;185</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;not&nbsp;'concepts'&nbsp;in&nbsp;args&nbsp;and&nbsp;not&nbsp;'doculects'&nbsp;in&nbsp;args:<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;186</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;idxs&nbsp;=&nbsp;[line[0]&nbsp;for&nbsp;line&nbsp;in&nbsp;cursor.execute(<br>
</tt></font></td></tr>
<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;187</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'select&nbsp;distinct&nbsp;ID&nbsp;from&nbsp;'+args['file']+';')]<br>
</tt></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;188</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>
</tt></font></td></tr>
<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;189</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;we&nbsp;evaluate&nbsp;the&nbsp;concept&nbsp;string<br>
</tt></font></td></tr>
<tr><td><small><font color="#909090"><strong>args</strong>&nbsp;= {'columns': 'ALIGNMENT|COGID|TOKENS|SUBGROUP|CONCEPT|PROTO_FORM|DOCULECT|FORM|NOTE', 'file': 'valzarpanotakana', 'remote_dbase': 'valzarpanotakana.sqlite3'}</font></small></td></tr></table><p><strong>&lt;class 'sqlite3.OperationalError'&gt;</strong>: no such table: valzarpanotakana
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=
('no such table: valzarpanotakana',)
<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>message&nbsp;=
'no such table: valzarpanotakana'


<!-- The above is a description of an error in a Python program, formatted
     for a Web browser because the 'cgitb' module was enabled.  In case you
     are not reading this in a Web browser, here is the original traceback:

Traceback (most recent call last):
  File "get_data.py", line 187, in &lt;module&gt;
    'select distinct ID from '+args['file']+';')]
OperationalError: no such table: valzarpanotakana

-->

